# Generated by Django 3.2.6 on 2021-09-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=0)),
                ('moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['moyenne'],
            },
        ),
    ]
